### ISSUE TITLE
Pure zsh ssh.zsh

### ISSUE THREAD

**Issue by anki-code** [xxh/zsh-portable#3]
Originally posted by @romkatv:
> I've used zsh-portable without xxh: https://www.reddit.com/r/zsh/comments/fiq9w2/bring_zsh_with_ohmyzsh_wherever_you_go_through/fkka097/. Works very well.

**Comment by anki-code** [comment]
I will call you "Romka-fast-fingers" :) You're great!

I've spent weeks to clear the concept and make xxh agile. And now it's easy to copy it on any faster language without dependencies as python.

You're copying files from host. It's not secure and I avoid it in xxh consciously.

**Comment by anki-code** [comment]
@romkatv If you're going to write xxh on pure zsh please add the link to xxh as the source of the idea and concept please.

**Comment by romkatv** [comment]
> > I created a pure Zsh script that allows you to do the same thing without xxh or python.
> 
> So it's a bit wrong :(

Oh man, sorry about that :-( I've added an errata to my Zsh post with a correction. `ssh.zsh` is *not* doing the same thing as xxh.

> If you're going to write xxh on pure zsh please add the link to xxh repo as the source of the idea and concept please.

I'll totally link to xxh if I ever decide to write xxh in zsh.

FWIW, here's how I see it. Bart has posted build instructions for a rootless zsh to a public mailing list. You've created a docker build file based on these instructions and published the resulting binary for everyone to use. I've used this binary in an open-source script. God bless open-source, right?

I'm not sure xxh can be credited for the idea or concept behind installing installing stuff over ssh. The technique of running `ssh -t 'do-stuff; shell -i'` has been used since forever. I login to my production machines via a script similar to `ssh.zsh` (although written in bash) that brings my admin scripts and tools for a ride. I copied bits and pieces from this script to create `ssh.zsh`. The only thing I used from xxh is the compiled zsh. I've also used a statically linked git but from another project.

I haven't yet looked at xxh. I really need to find time to. It sounds pretty cool! Keep it up, this project has potential.

**Comment by anki-code** [comment]
@romkatv I call "idea of xxh" three things that have never be together until I start xxh:

1. Portable shell could be build and uploaded to the host.
2. Plugin, color themes and environment could be with the portable shell on host
3. It could be done very common way using `ssh -t`, you know

Every this point looks simple and well known but now 2020 year and I try to search similar project there is no one. Tell me if you know. 

I spent around half of year to debug every part of this algo. I've started from zzh and have fail, then try with xonsh and win and now I back to zsh and it looks working.

The Bart`s post you mean was created after my questions. If I have not ask him and make noise about portable shell then there was no zsh-portable repo.

As you see we have puzzle with many details. I've passed long way from scratch to proof of concept and when you just copy every detail and tell "Look! I do the same!" it's a bit fun for me. Because yes, after a half of year of research anybody could rewrite this "simple things" on any language. What's a Lord! What's an open source! Ohhh.... ))

**Comment by anki-code** [comment]
So now your pure zsh solution is on top of reddit comments :) Hope it help to make Zsh for humans popular )

**Comment by romkatv** [comment]
> I just asking:
> 
> * please add xxh mention with repo link as original (source of) concept
> * please tell about ssh.zsh not as full replace xxh, until it be )

Done!

I feel you are upset. Is there anything I can do that would help?

**Comment by anki-code** [comment]
Thanks but you could done it without big disclaimers that I'm asking. It looks like you're joking on my reaction. Probably the big thing for me it's just another github repo for you. May be you're right.

**Comment by romkatv** [comment]
I think you are overreacting. I do want to help as much as I can though.

I mentioned that you are asking me to add these points because they look really weird to me and I don't truly understand why you wanted them added. If I added just my own words, I would risk misinterpreting what you wanted added, so I played it safe, to make *sure* you'll be satisfied, and copied the request verbatim.

Do you want it changed? How?

**Comment by romkatv** [comment]
> I think you are overreacting.

So here's how it looks. You create something useful, make it open source and free and announce it on reddit. Someone else creates a shell scripts that uses your stuff, puts this script in their public dotfiles repo and adds a comment to your post. There is zero critique in the comment, it just says look -- you can also use this stuff from pure zsh.

Success, right? And then you go kinda bonkers 🤷‍♂

**Comment by anki-code** [comment]
The ordinary way: tell people about the solution, get feedback and talking about the solution. In our current case you super fast made the replacement because pure zsh is native than python and the people`s attention has gone away. It's like Bill Gates will come to Mac presentation with new Win10. Let's stop discussion. It happened as happened. If you will create static binary of zsh with musl and make PR it will be more interesting than this thread.

**Comment by romkatv** [comment]
> If you will create static binary of zsh with musl and make PR it will be more interesting than this thread.

That's what I was working on before you've opened this issue. I'm not sure it's a good idea to continue.

**Comment by anki-code** [comment]
I don't know. May be I'm wrong and just want to get more attention because there is lack of feedback about xxh. May be it's not really working for people )

**Comment by romkatv** [comment]
The demand is likely low. I don't have a use-case for rootless zsh even though I ssh to different servers a lot. My whole circle of friends and acquaintances are computer people and yet I don't think I know anyone personally who would use this.

To clarify, I think copying files from local machine to remote when connecting over SSH is tremendously useful and I do this all the time. One of the main goals of the new version of zsh4humans that I'm working on is the ability to copy configs from one machine to another and have state being recreated exactly. There is `z4h ssh` that wraps `ssh` and automates config transfer. (I understand that this is the opposite of xxh principles but for me this is the most important thing.) The native dependencies (zsh and git), if not yet installed, can be installed by z4h automatically if the user has root/sudo privileges.

When I saw your announcement I thought that maybe I should toy with the idea of installing statically linked git and zsh. This wouldn't be totally out of the blue because z4h already can install some native binaries locally (e.g., fzf). I've found package repositories with statically linked git but kernel and architecture coverage is too low for my requirements. For zsh it's even lower -- there are no statically linked zsh binaries in any repository I know of. Your current solution works in common cases but it's not fully portable (e.g., it won't work on linux with a different program loader, such as on NixOS) so I cannot yet seriously consider using it in z4h. There are also no binaries for i386, arm, bsd, windows, etc.

So the way forward is either to create a new repository (e.g., release files under zsh-users/zsh, or a new repo at zsh-users/zsh-static) and build binaries for all platforms I care about (I think 9 or 10 platforms should do it) or find another way. I think it's likely not too difficult to build a fully-static zsh binary that can be placed in any directory and that just works without shell wrappers. Once the build script is figured out, building all binaries is not much work (I do it with gitstatusd already).

One alternative could be, for example, to utilize the existing packages from mature repositories (https://pkgs.org).

Another alternative is to look for projects that can bootstrap build environments and build on remote host. This would be best but I have the least experience here. This would in theory give maximum portability and security. Newer languages such as Rust and Go are good at this but when it comes to C it's all rather painful.

Just some random thoughts.

**Comment by anki-code** [comment]
> (I understand that this is the opposite of xxh principles but for me this is the most important thing.)

When I'm talking about copying I mean that `scp ~./.zshrc host:~/` is not the stable way in common case. Because user's zshrc may contains local specific setting, keys or something not working on remote host. If you're copying `.p10k` config/dir and you know that it has only user config and it's portable as is then it's ok for xxh conept. This type of config/dir could just be transferred.

Thank you for your thoughts! I've thought about the same problems but I've not enough experience in building linux libraries.

**Comment by romkatv** [comment]
> When I'm talking about copying I mean that `scp ~./.zshrc host:~/` is not the stable way in common case.

Yes, of course. Copying all environment variables, or all files, to a remote machine is a bad idea. Copying *whitelisted* environment variables is a fine idea and everyone does it. The same goes for files.

Perhaps I was just confused by the principles of xxh you've posted. They frankly don't make much sense to me but it's probably the language barrier.

E.g., you mention that building on the remote machine is bad. Could you elaborate why?

The documentation appears to make an impossible promise that no files outside of `~/.xxhdirectory ` will be affected. It's not a good idea to make impossible promises especially those that someone can rely on when using your code.

**Comment by anki-code** [comment]
> E.g., you mention that building on the remote machine is bad. Could you elaborate why?

It depends and as I understand is not actual to you. The reasons: no internet on the host, no building tools, security policy, not enough space or other resources. By default xxh should build the files locally. Putting the building process to remote host is next feature. I think I can implement it for someone in minutes but no real request now.

> no files outside 

I've added more info about it. Thanks!

**Comment by romkatv** [comment]
> > E.g., you mention that building on the remote machine is bad. Could you elaborate why?
> 
> I think I can implement it for someone in minutes but no real request now.

Thanks for the clarification. I was confused by your calling this a principle, which made it look like building on the remote machine is a bad idea even when there are no obstacles to it. Now I see that you consider building on remote host a potential feature.

**Comment by anki-code** [comment]
> it's not fully portable (e.g., it won't work on linux with a different program loader, such as on NixOS)

Why it is so extremely important? For example AppImage is not still support Alpine. But they tell about AppImage and many people who tried it were happy. For example on reddit one MacOS user tried AppImage and happy. 

May be you're working with special stack of linux os? I would be happy to support any linux version but I can't. The community help will be appreciated.

**Comment by romkatv** [comment]
> > it's not fully portable (e.g., it won't work on linux with a different program loader, such as on NixOS)
> 
> Why it is so extremely important?

It's not extremely important.
